# Generated by Django 5.1.3 on 2025-03-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watch_images/'),
        ),
        migrations.AddField(
            model_name='watch',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
