# Generated by Django 5.1.3 on 2025-03-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_watch_brand_watch_description_watch_image_watch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watch_images'),
        ),
    ]
